name: CI

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: 22
      - run: npm ci
      - run: |
          echo "VITE_API_GATEWAY_URL=${{ secrets.API_GATEWAY_URL }}" > .env
          npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: dist